# Development configuration for Thai Search Proxy Service

search_proxy:
  service_name: "thai-search-proxy"
  service_version: "1.0.0"
  environment: "development"
  
  # Tokenization configuration
  tokenization:
    primary_engine: "newmm"
    fallback_engines: ["attacut", "deepcut"]
    timeout_ms: 5000
    confidence_threshold: 0.7
    enable_compound_splitting: true
    preserve_original: true
    mixed_language_detection: true
  
  # Search execution configuration
  search:
    parallel_searches: true
    max_concurrent_searches: 3
    timeout_ms: 10000
    retry_attempts: 1
    retry_delay_ms: 100
    enable_fallback_search: true
    max_query_variants: 5
    deduplication_enabled: true
  
  # Result ranking configuration
  ranking:
    algorithm: "weighted_score"
    boost_exact_matches: 2.0
    boost_thai_matches: 1.5
    boost_compound_matches: 1.3
    decay_factor: 0.1
    min_score_threshold: 0.1
    max_results_per_variant: 100
    enable_score_normalization: true
  
  # Performance configuration
  performance:
    enable_metrics: true
    enable_detailed_logging: true
    max_query_length: 1000
    max_batch_size: 10
    memory_limit_mb: 128
    cache_enabled: true
    cache_ttl_seconds: 60
  
  # External services
  meilisearch:
    url: "http://localhost:7700"
    timeout_ms: 30000
    # api_key: set via environment variable
  
  # Logging and monitoring
  logging:
    level: "DEBUG"
    structured_logging: true
    enable_health_checks: true
    health_check_interval_seconds: 30
  
  # Feature flags
  features:
    enable_experimental_features: true
    enable_a_b_testing: false