services:
  thai-tokenizer:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - THAI_TOKENIZER_CUSTOM_DICTIONARY_PATH=data/dictionaries/thai_compounds.json
      - THAI_TOKENIZER_TOKENIZER_HANDLE_COMPOUNDS=true
      - THAI_TOKENIZER_TOKENIZER_ENGINE=newmm
      - THAI_TOKENIZER_DEBUG=false
      - THAI_TOKENIZER_MEILISEARCH_HOST=${EXISTING_MEILISEARCH_URL:-http://host.docker.internal:7700}
      - THAI_TOKENIZER_MEILISEARCH_API_KEY=${EXISTING_MEILISEARCH_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ../../data:/app/data
      - ../../logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - thai-tokenizer-network

networks:
  thai-tokenizer-network:
    driver: bridge